language: objective-c
osx_image: xcode9
rvm:
- 2.2
env:
  matrix:
  - TRAVIS_TAG="travis_test_6" PROJECT_NAME="testpackage" UNITY_PROJECT_PATH="buildproject"
    DEPLOY_UNITYPACKAGE="path set in deploy script"
  global:
  - secure: ocEySsKj7rRltKfsrL6EJjisf8lcEq1bHPUbIuS5Xc1XVB1QwIgITVwEN9nS+vVosj8Y7Dod+REFGyFbbzcABlxEqNz5UwqxxdVd12fcTxl3+cuTJtFGmykG1pFxhwpPT6aShLS6Ecq48MgipO3dG0BCYIGUUBaBClzFexCVoQHvz7/yQG7tL8tt4bE9s6BoeUvBwscjzODi35ZNrUNeWxmXLwkhOcZVVlt9O6p+W3/iIhWt5Nj6CK62+7fkOHJpX5lshAlE2BWF0WhyibuYZ4zP8alKK/Y+2d6sFOm/R6OITqhuBpfiDlb1DC+Ocfcbx6EjdN32y0udDIOYHNR6Dv/r05QM4Jj1wCDaz2W4EaVDhQRiz8gzmpLnr5g8Y1cNpsHzV22x3XbRWJRPWg+QZhtxqkMJFncCzxCncOZ8km7lpRgTuyzMS4cqRAT++vVtJXDK/cffAJitaF8KZV3AvfyyuzXRBWO31b+L5G5xL0WinmYLTXfTZccsVqeyAy3ZGfs9PvaibwK8Y00EL3khjH+TXF2XTWiKxtZNWAiJ5l53kVTp9Mrg2V6c/FGZQmb3V8Rojjp/ANGhFSv07Tx/FG9MGAKQ1GKbfc+UdNdpgL0hWK6NWB02hewtyCusZjrfbe/TvAmmmzGnur+AmF7NItOTvuYYHXhhmqUzEJNV43A=
  - secure: R3SBb25A6FD0h/YPLmtB1Aqb6enDXgPgjK9doGbnBcY9XSgS4p9Dg41HNGIiZaNIY7peG3s3ILPMrc6Eh/wYd4jn30rIlmFTKqno9MIVWqBczQP2yJqfHqUq6S3BCPCTmWzIz3VsGBaklT0g45uPdw9UtvwcxD14M5GTPSTGvaGyQTK/KW5Q3Fh6uDumbhzQIApNUlRdNFLuT90+14l40YxmhsbC7K9oRCSsw5m13jjfR6bQAz8BAESgMlhAWCIDZZV/pKocNUq0Z7VbmmeenZmaSQHp/SIFUyIwdh7JBPCE3fp49GCViVwzI0Nt6X0ZHeAXemEH9XBemfUUedy067STvU0higovr7Yl1mzcnTRxWHwVWv4AqcCZ49tKeFg5sAeP2YIoYP2y9TsOHW/PslPyEFQn4GzUDmz7dbg14Vk+eBPlEfAU+5FnnTQ0h7WNwSpikH8T/tQxCJlsIdRpAwLN5MbK3ic+4qkQG11vfFAvRQebT3reiq7CYx6C4cbaXRab7kvohxzMt50C1Jpq17fk97glxQIZPFdgRNWviQiT5a7N8q77CPLLooY6WfEtrYUl5XB42+FJZ+PIpFtz/HPpgpbFOJqy5HYuAb6GXA3Ig7z9m0RoWRpZOVyahzcdBqu4dE4oALujfwfrIYRI3R0u8dGXVsB4sUpnokuFVsQ=
  - secure: gHX6pXyAe32VjR07KpRePRFQfK5dy4dhigWswRTGuEShx41/KAvwqQQPQn3WiFbIQhvuMXwiNgShRxdgJnr5gTJQdmR9hqFaHWh2uo1Y6P2dxGLceljrD7gtZjnwKiqDMCHLFCJw5pgv1VtleMBTJq+neVia2E636G+uC1ZbKeyRCcJHKpN0eP5mkhaw+l5+vc85Du35LEOjExCB1aQilgbATauDhEnRHNH3JlGCHQNv1MorhLR5W1ZK1yROkclRflgJCCr4+AGHc6VH4+IefQtuMYKmuwLhLzOEdQeOfEnaFqjL9o0ImByvGa6imoK69YW1LEJWfd91Pzk96y7xnYqh4bwBBv/+db+u9K1a31iGdPlsNIpQGsbNl4xIULcKR3IXY94ZLiY2dACQxOSTIURJ4orKeuDq8WxSF792Se5kw82m7Rb2/IqwQ+lyyQKrDaehkqGgmkUk5lBpRPXYZFG3dLtye8gtDaL2DUSIj+4axkAp6i4srj2pjc1v0MuKkl0Z9sRNHFiGyBn/PleIJoT7iLQZmU3otHQcoxJUFQxnBE4Ck4dRAUwvxbws1oTTOb7ocMnT8yJnw3vfGWCXeCVODv81wHD8RwmlhkdxLN4AckYz3hrfsuMtq7qu4845QxIJ9pDqxoV3gVsJ9PtN25ASHBmy7oYSUMN6hQMlX20=

cache:
  directories:
  - "$UNITY_DOWNLOAD_CACHE"
before_install:
- chmod a+x ./travis-build/*.sh
install:
- cat /etc/hosts
- "./travis-build/install-unity.sh"
#- "./travis-build/download-license.sh"
script:
- "./travis-build/build.sh"
- "./travis-build/run-tests.sh"
after_success:
- "./travis-build/export-unity-package.sh"
before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"
deploy:
  provider: releases
  api_key:
    secure: Di3tD/tAKml9UDd326jAQrgdBwN8/8Ldb27Grb7zqCLXdoI/vI8raaapK5sRFjxIMoz+iPC/IAyXRz1ktSjKK5ZSXIKvaW0VC26lj0/Qd6q+TTYdc0xRqpTG49tpweFDOG95fu0cKJzGZ8kBQPfeQ8cxseh+9+CoKS4NyDeV06erc84aDBzbGZS4i3oUZ6DOD0klmImrKPQcS4cYako039oeKV8MPKNh5C8WutU5/cx3j+bJVu539q9ynWZ3Z88Wf1IINDqf2PyC+bzVSAd6QojmqKByVAHTsULa0t5+BtZZd76Hu8gcX4oR8a0HO/MYLIKEYWRRj4y7ZpM3V+K/BMDWr4+aERx5TNKUSI9BOFQapKULYlzCMLtan+fX5ZDAOnC4bRk9164STXVchRkWdrMmjV4dGhGIu7UEhpnoh3BhWy1BEB28pJjyeraEpB1kvbPssxb/ITo9VmMwpLLtw4ozCS1R6KWfP63djmoYKbYIAlMAzMjerfdIfgOct+MGo0gExTswV9lZOJtINSIigXEP4zHBWrqNemMd9HHV4LB/EjntKuxE+tqnYjwLCUMtyTZD5VnIjNl7/09Xvrjxol78I5exdBLRucR0rufLzpDb+Lhwpyiu/mb9crNH/0SS7YRvV/v8NZHewBwERo1FVzIVRpi7BPkW3qGukYYv0bY=
  file: "$DEPLOY_UNITYPACKAGE"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: YunSeok-Kang/travisci-test2
dd:
  secure: KQAolIoFj4QL6+yunu6l7bESpvQAmYBM8Ywt5ZQPrpxSgdJtGJUM/3QResEy8XX8mOz2/4b0C6kD0yl2fivOlNChypjmCYIVjh6NWAJ1u6MtarLtOMqjVdA1eIekz7WWeWAyU4TyOq++v6wulZsIIDRm8BAc8LBtW4qxYp9TTZcj/SBICAwuhgveL1oaBG+ecXlKXn3hGlC6VjumcshdmHeamdtXpTzcQgWAPEC+OIN2ahmKk3shZZzDMmkISh3J8le24rySrXeiMDlZqS6kHaNXsOOdSH3ueA3cLcLXO4eOZDXIky1syKvo64a6Dett6d7uQhuVRdyulL9em4Dvt+x3Dv1HR/nXSyUioFDleY2mK+b2YOiloa6jEKn8OV6xTWrmBSlWWD56Z4EAkgqN90xk22KwdyHuezRsyw7/MuxfUPVKGeev/2eH5WIj6KHVRFUUWMLZ8YPScgCjsOsK962B2v4AkEPsTVxKl9r73cJsAy3+wUwdErHWR/PobZ9PGJGobaCZmFTo62K5M/sB7l+wBZjaCPVzWBiObqU1qS0F2oVdIexUahIhHHa7XhkYVTB52HwpUhx6XCqcaKUaMCC3Q33uBUj5Ly69yTfR4y5NJv8/m84IHuZle4me5wsJHRy0YfkzH9S0jdAF8wl44iPUClySgAneUIclNgt6GDc=
